/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <mkl.h>
#include <cstdio>
#include <cmath>
/* Header for class MKLOperate */

#ifndef _Included_MKLOperate
#define _Included_MKLOperate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MKLOperate
 * Method:    mklAdd
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MKLOperate_mklAdd
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     MKLOperate
 * Method:    mklMinus
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MKLOperate_mklMinus
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     MKLOperate
 * Method:    mklMultiple
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MKLOperate_mklMultiple
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
